import type { Product } from '@/types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Elegant Ceramic Vase',
    description: 'A beautifully crafted ceramic vase, perfect for adding a touch of modern elegance to any room. Its minimalist design complements any decor style.',
    price: 45.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'ceramic vase',
    category: 'Home Decor',
    rating: 4.5,
    reviews: 120,
    tags: ['vase', 'ceramic', 'decor'],
  },
  {
    id: 2,
    name: 'Mid-Century Modern Chair',
    description: 'Iconic and comfortable, this chair features a solid wood frame and premium upholstery. A timeless piece for your living room or office.',
    price: 350.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'modern chair',
    category: 'Furniture',
    rating: 4.8,
    reviews: 85,
    tags: ['chair', 'furniture', 'wood'],
  },
  {
    id: 3,
    name: 'Abstract Canvas Art',
    description: 'Vibrant and expressive, this large canvas art piece becomes an instant focal point. Hand-painted by contemporary artists.',
    price: 180.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'abstract art',
    category: 'Wall Art',
    rating: 4.7,
    reviews: 95,
    tags: ['art', 'canvas', 'painting'],
  },
  {
    id: 4,
    name: 'Linen Throw Pillow',
    description: 'Soft, breathable, and stylish. This linen throw pillow adds texture and comfort to your sofa or bed. Available in multiple colors.',
    price: 29.99,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'throw pillow',
    category: 'Home Decor',
    rating: 4.9,
    reviews: 250,
    tags: ['pillow', 'linen', 'decor'],
  },
  {
    id: 5,
    name: 'Minimalist Desk Lamp',
    description: 'Sleek and functional, this LED desk lamp provides clear, adjustable light. Features a brushed metal finish and a slim profile.',
    price: 75.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'desk lamp',
    category: 'Lighting',
    rating: 4.6,
    reviews: 150,
    tags: ['lamp', 'lighting', 'desk'],
  },
  {
    id: 6,
    name: 'Acacia Wood Side Table',
    description: 'Crafted from sustainable acacia wood, this side table brings a natural, rustic charm to your space. Perfect next to a sofa or armchair.',
    price: 120.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'wood table',
    category: 'Furniture',
    rating: 4.8,
    reviews: 70,
    tags: ['table', 'wood', 'furniture'],
  },
  {
    id: 7,
    name: 'Geometric Wool Rug',
    description: 'Hand-tufted from 100% wool, this rug features a bold geometric pattern that adds warmth and character to any floor.',
    price: 299.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'wool rug',
    category: 'Rugs',
    rating: 4.7,
    reviews: 65,
    tags: ['rug', 'wool', 'geometric'],
  },
  {
    id: 8,
    name: 'Set of 4 Stoneware Mugs',
    description: 'Enjoy your favorite beverage in these earthy, durable stoneware mugs. Each mug has a unique reactive glaze finish.',
    price: 38.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'stoneware mugs',
    category: 'Kitchen',
    rating: 4.9,
    reviews: 310,
    tags: ['mugs', 'kitchen', 'stoneware'],
  },
];
