
import type { Product } from '@/types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Elegant Rose Print',
    description: 'A timeless and elegant print of a blooming rose, captured in stunning detail. Perfect for adding a touch of romance and sophistication to any room.',
    price: 2899.00,
    image: 'https://i.ibb.co/68Rz07D/elegant-rose.png',
    dataAiHint: 'ai generated rose',
    category: 'Floral Prints',
    rating: 4.8,
    reviews: 28,
    tags: ['rose', 'floral', 'classic'],
  },
  {
    id: 2,
    name: 'Cherry Blossom Peace',
    description: 'Bring a sense of calm and renewal into your space with this delicate cherry blossom print. A symbol of beauty and fleeting moments.',
    price: 2699.00,
    image: 'https://i.ibb.co/d2xVz9V/cherry-blossom.png',
    dataAiHint: 'ai generated cherry blossom',
    category: 'Floral Prints',
    rating: 4.9,
    reviews: 35,
    tags: ['cherry blossom', 'japanese', 'peaceful'],
  },
  {
    id: 3,
    name: 'Abstract Floral Medley',
    description: 'A vibrant and modern interpretation of a floral bouquet. This abstract print adds a pop of color and artistic flair to your decor.',
    price: 3699.00,
    image: 'https://i.ibb.co/yqgJj2F/abstract-floral.png',
    dataAiHint: 'ai generated abstract floral',
    category: 'Abstract Art',
    rating: 4.7,
    reviews: 19,
    tags: ['abstract', 'floral', 'modern'],
  },
  {
    id: 4,
    name: 'Enchanted Forest Canopy',
    description: 'Lose yourself in the lush greenery of this enchanted forest canopy print. A captivating piece that brings the magic of nature indoors.',
    price: 3499.00,
    image: 'https://i.ibb.co/P9tPq15/enchanted-forest.png',
    dataAiHint: 'ai generated forest',
    category: 'Nature Prints',
    rating: 4.9,
    reviews: 41,
    tags: ['forest', 'nature', 'green'],
  },
  {
    id: 5,
    name: 'Golden Wattle Sunshine',
    description: 'Capture the cheerful spirit of Australian flora with this bright and sunny golden wattle print. A perfect way to brighten any space.',
    price: 2499.00,
    image: 'https://i.ibb.co/KXVY0tX/golden-wattle.png',
    dataAiHint: 'ai generated wattle',
    category: 'Floral Prints',
    rating: 4.6,
    reviews: 15,
    tags: ['wattle', 'australian', 'yellow'],
  },
  {
    id: 6,
    name: 'Midnight Peony Dream',
    description: 'A dramatic and moody print of a deep, dark peony. This captivating artwork adds a touch of mystery and elegance to your walls.',
    price: 3199.00,
    image: 'https://i.ibb.co/GvxB12p/midnight-peony.png',
    dataAiHint: 'ai generated dark peony',
    category: 'Floral Prints',
    rating: 4.8,
    reviews: 22,
    tags: ['peony', 'dark floral', 'dramatic'],
  },
  {
    id: 7,
    name: 'Lavender Field Serenity',
    description: 'Transport yourself to the calming lavender fields of Provence with this serene and beautiful landscape print. Promotes relaxation and peace.',
    price: 3299.00,
    image: 'https://i.ibb.co/sK4XfVv/lavender-field.png',
    dataAiHint: 'ai generated lavender',
    category: 'Nature Prints',
    rating: 5.0,
    reviews: 52,
    tags: ['lavender', 'landscape', 'serene'],
  },
  {
    id: 8,
    name: 'Wildflower Symphony',
    description: 'A delightful and chaotic arrangement of various wildflowers. This print is a celebration of nature\'s untamed beauty and diversity.',
    price: 2999.00,
    image: 'https://i.ibb.co/hKPrb8H/wildflower-symphony.png',
    dataAiHint: 'ai generated wildflowers',
    category: 'Floral Prints',
    rating: 4.7,
    reviews: 31,
    tags: ['wildflowers', 'colorful', 'bohemian'],
  },
];
