import type { Product } from '@/types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Elegant Rose Print',
    description: 'A beautifully detailed print of a blooming rose, perfect for adding a touch of classic elegance to any room. Its soft colors complement any decor style.',
    price: 45.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'rose flower',
    category: 'Floral Prints',
    rating: 4.5,
    reviews: 120,
    tags: ['rose', 'flower', 'print'],
  },
  {
    id: 2,
    name: 'Abstract Floral Medley',
    description: 'A vibrant and modern abstract interpretation of a field of wildflowers. A timeless piece for your living room or office.',
    price: 350.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'abstract flowers',
    category: 'Abstract Art',
    rating: 4.8,
    reviews: 85,
    tags: ['abstract', 'floral', 'art'],
  },
  {
    id: 3,
    name: 'Serene Lily Canvas',
    description: 'Vibrant and expressive, this large canvas art piece captures the serene beauty of water lilies. Hand-painted by contemporary artists.',
    price: 180.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'lily flower',
    category: 'Wall Art',
    rating: 4.7,
    reviews: 95,
    tags: ['art', 'canvas', 'painting'],
  },
  {
    id: 9,
    name: 'Personalized Bear Hug T-Shirt',
    description: 'A charming and soft pink t-shirt featuring a cute teddy bear, elegantly framed by delicate flowers. Can be personalized with a name for a truly unique gift.',
    price: 55.00,
    image: 'https://i.ibb.co/3k5fCnc/image.png',
    dataAiHint: 'teddy bear shirt',
    category: 'Apparel',
    rating: 4.9,
    reviews: 180,
    tags: ['t-shirt', 'personalized', 'kids'],
  },
  {
    id: 5,
    name: 'Minimalist Tulip Sketch',
    description: 'A sleek and modern line art print of a single tulip. Perfect for minimalist and contemporary interiors.',
    price: 75.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'tulip flower',
    category: 'Line Art',
    rating: 4.6,
    reviews: 150,
    tags: ['tulip', 'minimalist', 'art'],
  },
  {
    id: 6,
    name: 'Peony Bouquet Print',
    description: 'A lush and romantic print of a vibrant peony bouquet. Adds a pop of color and feminine charm to your decor.',
    price: 120.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'peony flower',
    category: 'Floral Prints',
    rating: 4.8,
    reviews: 70,
    tags: ['peony', 'bouquet', 'flower'],
  },
  {
    id: 4,
    name: 'Cherry Blossom Branch',
    description: 'A delicate and airy print of a cherry blossom branch in full bloom. Brings a sense of peace and tranquility to your space.',
    price: 29.99,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'cherry blossom',
    category: 'Floral Prints',
    rating: 4.9,
    reviews: 250,
    tags: ['cherry blossom', 'flower', 'print'],
  },
  {
    id: 7,
    name: 'Geometric Floral Pattern',
    description: 'A unique print combining geometric shapes with delicate floral elements. A modern take on classic floral art.',
    price: 299.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'geometric floral',
    category: 'Geometric Art',
    rating: 4.7,
    reviews: 65,
    tags: ['rug', 'wool', 'geometric'],
  },
  {
    id: 8,
    name: 'Vintage Botanical Set',
    description: 'A set of four vintage-inspired botanical prints. Perfect for creating a beautiful gallery wall.',
    price: 38.00,
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'vintage flowers',
    category: 'Vintage Prints',
    rating: 4.9,
    reviews: 310,
    tags: ['vintage', 'botanical', 'set'],
  },
];
